#!/bin/bash

# simple port knocking to unlock a linux machine

# first check that the knock command is available...
command -v knock >/dev/null 2>&1 || { echo >&2 "Requires 'knock' but it's not installed.  Exiting."; exit 1; }

# change this!
BASTION_IP="12.12.12.12" # insert your target ip here, or we can parameterise this

# change these!
UNLOCK_PORTS="1234 1235 1236" # make up some ports to lock and unlock 

# change these!
LOCK_PORTS="1234 1235 1237"

if [[ $1 == 'unlock' ]]; then

	# send knock
	knock -v -d 350 $BASTION_IP $UNLOCK_PORTS
	
	# test ssh
	nc -z -v -w2 $BASTION_IP 22

elif [[ $1 == 'lock' ]]; then

	# send knock
	knock -v -d 350 $BASTION_IP $LOCK_PORTS

else
	echo "required parameter 'lock' or 'unlock'."
fi

	
